# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [3]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [4]:
#todo: 
import numpy as np

# Crear un array del 0 al 9
array = np.arange(10)

print(array)

[0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [6]:
#todo:
import numpy as np

# Crear un array de 5 ceros
array = np.zeros(5)
print(array)

# Cambiar el tercer elemento (índice 2) a 5
array[2] = 5

print(array)

[0. 0. 0. 0. 0.]
[0. 0. 5. 0. 0.]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [7]:
import numpy as np

# Generar una matriz 3x3 de números aleatorios entre 0 y 1
matriz = np.random.rand(3, 3)

print(matriz)

[[0.87173616 0.52972717 0.50275507]
 [0.66938598 0.14634465 0.67194573]
 [0.33570655 0.6989443  0.35555299]]


In [ ]:
#todo: 


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [8]:
#todo:
import numpy as np
import random

# Array inicial
arr = np.array([10, 20, 30, 40, 50])

# 1. Sumar 5 a cada elemento
arr_suma = arr + 5

# 2. Multiplicar por un número aleatorio
numero_aleatorio = random.random()  # Genera un número aleatorio entre 0 y 1
arr_final = arr_suma * numero_aleatorio

print("Array original:", arr)
print("Array después de sumar 5:", arr_suma)
print(f"Array después de multiplicar por {numero_aleatorio}:", arr_final)

Array original: [10 20 30 40 50]
Array después de sumar 5: [15 25 35 45 55]
Array después de multiplicar por 0.855961220333342: [12.83941831 21.39903051 29.95864271 38.51825492 47.07786712]


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [9]:
#todo:
import numpy as np

# Crear una matriz identidad de 4x4
matriz_identidad = np.eye(4)

print(matriz_identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [10]:
#todo: 
import numpy as np

# Crear un array con números pares entre 0 y 20
array = np.arange(0, 21, 2)

# Operaciones básicas
suma = array + 5          # Sumar 5 a cada elemento
resta = array - 3         # Restar 3 a cada elemento
multiplicacion = array * 2  # Multiplicar por 2 cada elemento
division = array / 4      # Dividir cada elemento entre 4

# Imprimir resultados
print("Array original:", array)
print("Array después de la suma:", suma)
print("Array después de la resta:", resta)
print("Array después de la multiplicación:", multiplicacion)
print("Array después de la división:", division)


Array original: [ 0  2  4  6  8 10 12 14 16 18 20]
Array después de la suma: [ 5  7  9 11 13 15 17 19 21 23 25]
Array después de la resta: [-3 -1  1  3  5  7  9 11 13 15 17]
Array después de la multiplicación: [ 0  4  8 12 16 20 24 28 32 36 40]
Array después de la división: [0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
